#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

export SUDO_EDITOR=vim
export VISUAL=vim
export EDITOR=vim
export PATH=~/Projects/schnapps/install/bin:~/local/bin:$PATH

source ~/.bash_alias
